quarkus.application.name=notification-service
quarkus.http.port=8006

# RabbitMQ Configuration
quarkus.rabbitmq.host=localhost
quarkus.rabbitmq.port=5672
quarkus.rabbitmq.username=guest
quarkus.rabbitmq.password=guest

# Mail Configuration
quarkus.mailer.host=localhost
quarkus.mailer.port=1025
quarkus.mailer.from=noreply@yellowkart.com

# OpenAPI
quarkus.smallrye-openapi.info-title=Notification Service API
quarkus.smallrye-openapi.info-version=1.0.0
