quarkus.application.name=order-service
quarkus.http.port=8004

# Database Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=yellowkart
quarkus.datasource.password=yellowkart123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/yellowkart_db

# ORM Configuration
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# OpenAPI
quarkus.smallrye-openapi.info-title=Order Service API
quarkus.smallrye-openapi.info-version=1.0.0
