quarkus.application.name=cart-service
quarkus.http.port=8003

# Redis Configuration
quarkus.redis.hosts=localhost:6379

# OpenAPI
quarkus.smallrye-openapi.info-title=Cart Service API
quarkus.smallrye-openapi.info-version=1.0.0
